### ISSUE TITLE
`RiquSamplingResult` object has no attribute `_result`

### ISSUE THREAD

**Issue by Jacomichi** [qiqb-osaka/quri-parts-riqu#17]
In the `__repr__` of `RiquSamplingResult`, `self._result` is called, but `self._result` is not defined.
https://github.com/qiqb-osaka/quri-parts-riqu/blob/39d34647a168e113bd68be629d1f7e43da90f74f/quri_parts/riqu/backend/sampling.py#L185-L186

# How to Reproduce
```python
from math import pi

from quri_parts.circuit import QuantumCircuit
from quri_parts.riqu.backend import RiquConfig, RiquSamplingBackend

circuit = QuantumCircuit(2)
circuit.add_H_gate(0)
circuit.add_CNOT_gate(0, 1)

config = RiquConfig.from_file(path="./config.toml",section="default")
backend = RiquSamplingBackend(config=config)

job = backend.sample(circuit, n_shots=1000)
repr(job.result())
```

**Error message**
```bash
AttributeError: 'RiquSamplingResult' object has no attribute '_result'
```

# version
quri-parts                0.18.0
quri-parts-riqu           0.3.0

**Comment by snuffkin** [comment]
@Jacomichi 
Thanks for your report!
Fixed it in pull request #19.
